### ISSUE TITLE
Help by implementing GlitchTip adapter 🛰

### ISSUE THREAD

**Issue by Meldiron** [utopia-php/logger#4]
# Introduction

All Utopia libraries focus on supporting multiple adapters such as storage, database, cache or logger. We currently support _only_ 3 providers for Logger library, but we are looking to increase this number! By preparing easy-to-follow instructions, we believe anyone can implement a new provider and get their contributions count up 😎

Your task is to implement **GlitchTip** adapter into our Logger library. You can find a complete in-depth tutorial in our official [tutorial for adding a new logger adapter](https://github.com/utopia-php/logger/blob/dev/docs/tutorials/add-logger-adapter.md). To find out more about GlitchTip, check out their [Website](https://glitchtip.com/).

### Tasks summary:

- [ ]  Read thought our [tutorial](https://github.com/utopia-php/logger/blob/dev/docs/tutorials/add-logger-adapter.md)
- [ ] Fork & clone `utopia-php/logger` (this repository)
- [ ] Switch to branch `feat-add-glitchtip-adapter`
- [ ] Create file for your provider in `src/Logger/Adapter/GlitchTip.php` and implement it
- [ ] Add your provider into `PROVIDERS` array in `src/Logger/Logger.php`
- [ ]  Implement a test for your provider in ``
- [ ]  Push changes and submit a pull request
- [ ]  Inside your PR, add screenshots of your test log pushed into GlitchTip

If you need any help, reach out to us on Appwrite [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by MaheshAravindV** [comment]
Hey, I would like to work on this.

**Comment by stnguyen90** [comment]
@MaheshAravindV, I don't think it is 🧐 Are you still interested in working on this?

**Comment by bhardwajparth51** [comment]
Hey, is this still open? I'd love to work on it! I've looked at the existing adapterssince GlitchTip is Sentry-compatible, the implementation should follow a similar structure. Could you assign it to me?
